### ISSUE TITLE
Consider Adding HDBSCAN and other clustering algorithms that work with distance matrices

### ISSUE THREAD

**Issue by adamrt27** [BRANCHlab/metasnf#1]
Right now you use spectral clustering to generate clusters, but I think adding the ability for the user to choose to use HDBSCAN could be interesting. There are a couple of articles that explain the algorithm well and compare it to others.

* overview of algorithm: https://pberba.github.io/stats/2020/01/17/hdbscan/
* comparison to other algorithms: https://hdbscan.readthedocs.io/en/latest/comparing_clustering_algorithms.html#spectral-clustering
* R implementation: https://cran.r-project.org/web/packages/dbscan/vignettes/hdbscan.html\

I think that overall, adding more options for how the data is clustered would be great, as it would allow users more flexibility. Or implementing in random choosing of clustering methods for the metaclustering part of the algorithm. This would allow for even more clustering solutions and reduce overfitting to solutions that spectral clustering is biased towards.

**Comment by pvelayudhan** [comment]
Thanks for the suggestion! I do agree more options for clustering the final result would be useful and does make a lot of sense with the overall purpose of the package. I will look into this next week.

**Comment by pvelayudhan** [comment]
Hi Adam,

Sorry about the delay! I've just recently completed the vignette outlining how to change the clustering algorithms used by the package. There's an example at the bottom that showcases using dbscan, but not in an automated fashion. With our test data (the original test demo used in the SNFtool vignettes), getting the dbscan hyperparameters just right required a lot of effort - so much so that it would just not be practical to try and find those hyperparameters by grid-searching while running the `batch_snf` function. 

For dbscan and other clustering algorithms that require human intervention to get the hyperparameters correct, there is documentation showing how to pull the final similarity matrices out yourself, convert them to distance matrices, and work through the clustering algorithms as intended.

But for any clustering algorithm for which the process of converting a similarity matrix to cluster solution can be 100% automated while still performing reasonably well, the vignette outlines how you can provide a function to the automated SNF process. If there's any function you end up putting together that you think would be a nice addition to the package, feel free to submit a pull request (or post about it again here)!

Vignette: [https://branchlab.github.io/metasnf/articles/clustering_algorithms.html](https://branchlab.github.io/metasnf/articles/clustering_algorithms.html)
