### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by ghost** [BRANCHlab/metasnf#13]
Hello! I really love all the new functionality of the package - as I was trying them, a few did not seem to run as intended however:

```
> mc_manhattan_plot(rep_solns, data_list = data_list)
Error in `tidyr::pivot_longer()`:
! `cols` must select at least one column.
```
Here, I believe the bug is in line 52

```
> batch_nmi(data_list, solutions_matrix$solutions_matrix)
[1] "Calculating NMIs for f39_severe_neonatal_morbidity.x (feature 1/235)..."
Error in feature_dl[[1]] : subscript out of bounds
```
In this bug, I believe the issue is in the call to `collapse_dl`. When I swap the call with my original data frame in line 5, `batch_nmi` worked smoothly.
i.e.
```
dl_df <- clinical_associations.pe 
```

If it is helpful, I generated my data_list by passing a list of lists!

**Comment by pvelayudhan** [comment]
Thanks for flagging these! I believe the first one is the result of building the "rep_solns" dataframe not ultimately being an **extended_solutions_matrix** that was columns ending in `_pval`. Those `_pval` columns are what get plotted in the `mc_manhattan_plot`. I realize that distinction is really not made clear anywhere in the function's documentation or that ambiguous tidyr error message lol. Could that be what is happening (i.e., was `rep_solns` made out of a regular `solutions_matrix` rather than `extended_solutions_matrix`)? If so (and even if not), I'll improve the error message and make it a little clearer what the rep_solns parameter is supposed to be made from. Really it shouldn't even be called rep_solutions at all, it should just take as an argument any `extended_solutions_matrix`. 

--------

For the second bug, I was able to replicate the error with this example:

```
library(metasnf)

data_list <- generate_data_list(
    list(anxiety, "anxiety", "behaviour", "ordinal"),
    list(anxiety, "anxiety", "behaviour", "ordinal"),
    uid = "unique_id"
)

settings_matrix <- generate_settings_matrix(
    data_list,
    nrow = 5,
    max_k = 50
)

solutions_matrix <- batch_snf(data_list, settings_matrix)

feature_nmis <- batch_nmi(data_list, solutions_matrix)
```

Notably this data list has the same feature name twice - something that can cause issues and that I'll make sure to add a warning about. Your last output line showing the feature name `f39_severe_neonatal_morbidity.x` instead of simply `f39_severe_neonatal_morbidity` indicates that the `collapse_dl()` output was given a data list that has `f39_severe_neonatal_morbidity` at least two times, and hence when converted into dataframe format, those replicates get assigned `f39_severe_neonatal_morbidity.x`, `f39_severe_neonatal_morbidity.y`, and so on. `feature_dl` ends up becoming empty because it searches for `f39_severe_neonatal_morbidity` and can't find it. 

That is at least my guess of what is happening - could you check to see if your data list has any duplicates of the feature name `f39_severe_neonatal_morbidity` being passed in?

--------

Assuming that's what's going on for both things, I'll make sure to update the package to:

1. Update batch_nmi documentation to rename the `rep_solutions` argument to `extended_solutions_matrix`
2. Add in a check in `generate_data_list()` to raise an error for duplicate feature names
3. Add in a check in `mc_manhattan_plot` (and the other manhattan plots) to flag data lists with duplicate feature names

**Comment by ghost** [comment]
Bug 1: Yes, I can confirm! `rep_solns` was created with a solutions matrix.  Thank you so much for diagnosing the issue!
Bug 2: You just caught a silent error in my analysis!!!! Thank you!!! I did have duplicate features after generating my list of lists with `apply` incorrectly.

I will let you know if I still get unexpected output, otherwise I appreciate your time and all your help!

**Comment by pvelayudhan** [comment]
No problem and thanks again for pointing these out!
